AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-back

  Sample SAM Template for cloud-back

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 3
    MemorySize: 128

Resources:

  StateMachineInvite:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: StateMachineInvite
      DefinitionUri: statemachine/family_invite.asl.json
      DefinitionSubstitutions: 
        SendSharingInviteArn: !GetAtt SendSharingInvite.Arn
        CheckRespondArn: !GetAtt CheckRespond.Arn
        NotifyAcceptedArn: !GetAtt NotifyAccepted.Arn
        NotifyDeclinedArn: !GetAtt NotifyDeclined.Arn
      Events:
        StateMachineInvite:
          Type: Api
          Properties:
            Path: /invite
            Method: post
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref SendSharingInvite
        - LambdaInvokePolicy:
            FunctionName: !Ref CheckRespond
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifyAccepted
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifyDeclined

  SendNotification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sendNotification/
      Handler: send_notification.send_notification
      Runtime: python3.9
      Role: arn:aws:iam::070424787807:role/AmazonSESFULLAccess
      Architectures:
        - x86_64
      Events:
        SendInvite:
          Type: Api
          Properties:
            Path: /notify
            Method: post

  SendSharingInvite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sendInvite/
      Handler: send_invite.send_email
      Runtime: python3.9
      Architectures: 
        - x86_64
      Policies:
        - DynamoDBWritePolicy:
            TableName: Sharing
        - DynamoDBReadPolicy:
            TableName: Sharing
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
            Resource: '*'
  
  CheckRespond:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: checkRespond/
      Handler: check_respond.check_respond
      Runtime: python3.9
      Architectures: 
        - x86_64
    Policies:
      - DynamoDBReadPolicy:
          TableName: Sharing
      - DynamoDBWritePolicy:
          TableName: Sharing

  NotifyAccepted:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: notifyAccepted/
      Handler: notify_accepted.notify_accepted
      Runtime: python3.9
      Architectures: 
        - x86_64
    Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
            Resource: '*'

  NotifyDeclined:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: notifyDeclined/
      Handler: notify_declined.notify_declined
      Runtime: python3.9
      Architectures: 
        - x86_64
    Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
            Resource: '*'

  SendSharingNotification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: shareFileFolder/
      Handler: share_file_folder.share_file_folder
      Runtime: python3.9
      Architectures: 
        - x86_64
      Events:
        SendEmail:
          Type: Api
          Properties:
            Path: /shareFile
            Method: post
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
            Resource: '*'
        - DynamoDBWritePolicy:
            TableName: SharingLink

  CheckIsLinkValid:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: checkValidLink/
      Handler: check_link.check_status
      Runtime: python3.9
      Architectures: 
        - x86_64
      Events:
        SendEmail:
          Type: Api
          Properties:
            Path: /checkIsLinkValid
            Method: post
      Policies:
        - DynamoDBWritePolicy:
            TableName: SharingLink
        - DynamoDBReadPolicy:
            TableName: SharingLink

  DownloadFolder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: downloadFolder/
      Handler: download_folder.download_all_files
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DownloadFile:
          Type: Api
          Properties:
            Path: /downloadFolder
            Method: post
      Policies:
        - S3FullAccessPolicy:
            BucketName: files-cloud-back
        - DynamoDBReadPolicy:
            TableName: metadata-cloud-back
  
  ResolveInvite:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: resolveInvite/
      Handler: resolve_invite.resolve_invite
      Runtime: python3.9
      Architectures: 
        - x86_64
      Events:
        AcceptInvite:
          Type: Api
          Properties:
            Path: /resolveInvite
            Method: put
      Policies:
        - DynamoDBWritePolicy:
            TableName: Sharing
        - DynamoDBReadPolicy:
            TableName: Sharing
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
            Resource: '*'

  GetFamilyMember:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getFamilyMember/
      Handler: get_family_member.get_username
      Runtime: python3.9
      Architectures: 
        - x86_64
      Events:
        AcceptInvite:
          Type: Api
          Properties:
            Path: /getFamily
            Method: post
      Policies:
        - DynamoDBReadPolicy:
            TableName: Sharing
  
  GetInvitations:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getInvitations/
      Handler: get_invitations.get_invitations
      Runtime: python3.9
      Architectures: 
        - x86_64
      Events:
        SendEmail:
          Type: Api
          Properties:
            Path: /getInvitations/{username}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: Sharing   

  ModifyInvitation:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modifyInvitation/
      Handler: modify_invitation.modify_invitation
      Runtime: python3.9
      Architectures: 
        - x86_64
      Events:
        SendEmail:
          Type: Api
          Properties:
            Path: /modifyInvitation
            Method: put
      Policies:
        - DynamoDBReadPolicy:
            TableName: Sharing 
        - DynamoDBWritePolicy:
            TableName: Sharing

  CreateFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createFile/
      Handler: create_file.create
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateFile:
          Type: Api
          Properties:
            Path: /create
            Method: post
      Policies:
        - DynamoDBWritePolicy:
            TableName: metadata-cloud-back
        - S3WritePolicy:
            BucketName: files-cloud-back

  GetAllFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getAllFiles/
      Handler: get_all.get_all_for_user
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetAllFiles:
          Type: Api
          Properties:
            Path: /{username}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: metadata-cloud-back

  MoveFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: moveFile/
      Handler: move_file.move
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        MoveFileFunction:
          Type: Api
          Properties:
            Path: /move
            Method: put
      Policies:
        - DynamoDBReadPolicy:
            TableName: metadata-cloud-back
        - DynamoDBWritePolicy:
            TableName: metadata-cloud-back
        - S3FullAccessPolicy:
            BucketName: files-cloud-back

  DeleteOneFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: deleteFile/
      Handler: delete_file.delete_one_file
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DeleteOneFileFunction:
          Type: Api
          Properties:
            Path: /delete
            Method: put
      Policies:
        - DynamoDBCrudPolicy:
            TableName: metadata-cloud-back
        - S3FullAccessPolicy:
            BucketName: files-cloud-back

  DownloadFile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: downloadFile/
      Handler: download_file.download_from_s3
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DownloadFile:
          Type: Api
          Properties:
            Path: /download
            Method: post
      Policies:
        - S3FullAccessPolicy:
            BucketName: files-cloud-back
            
  FileMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: metadata-cloud-back
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: files-cloud-back

  ModifyFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modifyFile/
      Handler: modify_file.update_file
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateFile:
          Type: Api
          Properties:
            Path: /update
            Method: put
      Policies:
        - DynamoDBWritePolicy:
            TableName: metadata-cloud-back
        - DynamoDBReadPolicy:
            TableName: metadata-cloud-back