AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-back

  Sample SAM Template for cloud-back

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda1
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  
  CreateFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createFile/
      Handler: create_file.create
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateFile:
          Type: Api
          Properties:
            Path: /create
            Method: post
      Policies:
        - DynamoDBWritePolicy:
            TableName: FileMetaDataTable

  FileMetaDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: FileMetaDataTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1