AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-back

  Sample SAM Template for cloud-back

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 3
    MemorySize: 128

Resources:

  CreateFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createFile/
      Handler: create_file.create
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateFile:
          Type: Api
          Properties:
            Path: /create
            Method: post
      Policies:
        - DynamoDBWritePolicy:
            TableName: metadata-cloud-back
        - S3WritePolicy:
            BucketName: files-cloud-back

  GetAllFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getAllFiles/
      Handler: get_all.get_all_for_user
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetAllFiles:
          Type: Api
          Properties:
            Path: /{username}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: metadata-cloud-back

  MoveFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: moveFile/
      Handler: move_file.move
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        MoveFileFunction:
          Type: Api
          Properties:
            Path: /move
            Method: put
      Policies:
        - DynamoDBReadPolicy:
            TableName: metadata-cloud-back
        - DynamoDBWritePolicy:
            TableName: metadata-cloud-back
        - S3FullAccessPolicy:
            BucketName: files-cloud-back

  DeleteOneFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: deleteFile/
      Handler: delete_file.delete_one_file
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DeleteOneFileFunction:
          Type: Api
          Properties:
            Path: /delete
            Method: put
      Policies:
        - DynamoDBCrudPolicy:
            TableName: metadata-cloud-back
        - S3FullAccessPolicy:
            BucketName: files-cloud-back

  DownloadFile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: downloadFile/
      Handler: download_file.download_from_s3
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DownloadFile:
          Type: Api
          Properties:
            Path: /download
            Method: post
      Policies:
        - S3FullAccessPolicy:
            BucketName: files-cloud-back


  FileMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: metadata-cloud-back
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: files-cloud-back
